stages:
  - build-check
  - build-staging
  - build-production

image: docker:stable
variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "" # HOTFIX?

services:
  - docker:dind

build-check:
  stage: build-check
  script:
    - docker build -t registry.gitlab.com/clovrlabs/elenwallet/server:$CI_COMMIT_REF_NAME -f ./Dockerfile .
  rules:
    - if: '$CI_COMMIT_REF_NAME != "clovrwallet-develop" &&  $CI_PIPELINE_SOURCE == "merge_request_event"' 

build-staging:
  stage: build-staging
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker build -t registry.gitlab.com/clovrlabs/elenwallet/server:$CI_COMMIT_REF_NAME -f ./Dockerfile .
    - docker push registry.gitlab.com/clovrlabs/elenwallet/server:$CI_COMMIT_REF_NAME
  rules:
    - if: '$CI_COMMIT_REF_NAME == "clovrwallet-develop" && $CI_PIPELINE_SOURCE != "merge_request_event"'

build-production:
  stage: build-production
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker build -t registry.gitlab.com/clovrlabs/elenwallet/server:$CI_COMMIT_TAG -f ./Dockerfile .
    - docker push registry.gitlab.com/clovrlabs/elenwallet/server:$CI_COMMIT_TAG
  rules:
    - if: '$CI_COMMIT_TAG =~ /^\d+\.\d+\.\d+$/'


